image: node:18

variables:
  GIT_DEPTH: "0"

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public/ 2>/dev/null || true
    - cp .gitignore .public/ 2>/dev/null || true
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
